### ISSUE TITLE
Rough Stone Bricks/Tiles durability

### ISSUE THREAD

**Issue by BeeEnjoyer** [unforbidable/tfcplus-bids#11]
Not quite sure if this is a bug, but rough stone tiles/bricks have laughably low durability even compared to cobblestone, getting mined by a pickaxe in a fraction of a second. Since they also drop when destroyed by hand I assume this might be the intended behavior for the pre-metal gameplay, but either way I'd recommend increasing time to mine, or perhaps switching the preferred tool to adze and removing drop by hand.

UPD: it seems that shovels also count as correct tool. Not sure if it's a bug or not, but writing it here in case it is.

Hope this helps.

**Comment by unforbidable** [comment]
I think what you are seeing is that rough stone blocks are very easy to break, even with hand, when there is no block above them. This is intended, and it kinda makes sense for walls, generally. However, I do appreciate that it makes floors and ceilings too easy to break by accident, and might not be such a good and practical idea after all.

**Comment by BeeEnjoyer** [comment]
While I still remember: aquifier blocks also seem to have no durability whatsoever, breaking instantly with bare hands or any tool. Is this also an intended feature?

**Comment by unforbidable** [comment]
No, not intentional.

Hopefully these issues should be fixed or improved in v0.46.0.
